services:
  - type: web
    runtime: docker
    name: siptrack
    region: virginia
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    autoDeployTrigger: commit
    envVars:
      - key: BUN_PUBLIC_CLERK_PUBLISHABLE_KEY
        sync: false
